### PR TITLE
move from git.uis

### PR DESCRIPTION
**Pull request by abrahammartin**

### CODE REVIEW

**Review by rjw57 — APPROVED** [review]

**Comment by rjw57** [comment]
Will merge if travis is happy.

**Comment by rjw57** [comment]
Travis is unhappy, @abrahammartin can you re-work?

**Comment by abrahammartin** [comment]
I don't get it, I don't know why now is working...

**Comment by rjw57** [comment]
Well, whatever it was, it doesn't seem to be related to this PR so merging.

**Pull request merged**
